Add DonorProvider step
gigs/embeds-react-native pull request #11
Opened 2024-04-24 21:46 UTC by dharmadeveloper108

This PR adds a step and a corresponding form for the case of a porting that is missing `donorProvider`.

## Screencasts

https://github.com/gigs/embeds-react-native/assets/56159524/8b8a762e-4848-41f7-b6e7-abd25354931f

https://github.com/gigs/embeds-react-native/assets/56159524/b1f46692-c8f3-4c8a-896d-92424e1f7920

2024-05-02 08:58 UTC, gigsanna requested changes

2024-05-02 08:58 UTC, gigsanna commented on src/PortingEmbed/PortingFormContainer.tsx
> +          porting={subscription.porting}
Should `isSubmitting` and `error` props also be passed here?

2024-05-02 08:58 UTC, gigsanna commented on src/PortingEmbed/__tests__/DonorProviderForm.test.tsx
> +    await waitFor(() => {
You're not supposed to have multiple assertions in one `waitFor` ([source](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#having-multiple-assertions-in-a-single-waitfor-callback)), any error thrown within this block will result in re-running the callback. You also perform a user action in there, which is also not allowed (see the next item in the [list](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#performing-side-effects-in-waitfor))

So the test would be 
```
render(...)

const button = await screen.findByText('Save')
expect(button).toBeDisabled()

fireEvent.press(button)

await waitFor(() => expect(onSaveMock).not.toHaveBeenCalled())

```

Same goes for other tests 🙂

2024-05-02 08:58 UTC, gigsanna commented on src/components/Dropdown.tsx
> +    onSelect('')
Why do we need this?

2024-05-02 08:58 UTC, gigsanna commented on docs/porting-embed.md
> +| `donorProvider`               | N/A                         |
Description for the `renderDropdown` prop (or a different name) would be helpful too

2024-05-02 08:58 UTC, gigsanna commented on src/PortingEmbed/CustomOptionsProvider.tsx
> +  renderDropdown?: (
From the name I assumed it's just any dropdown, only after reading where it's used I understood that it's specific to providers, the name should reflect that.

2024-05-02 09:06 UTC, dharmadeveloper108 commented on src/PortingEmbed/__tests__/DonorProviderForm.test.tsx
> +    await waitFor(() => {
ohhhh awesome thank you so much!! 👌 🤠

2024-05-02 09:15 UTC, dharmadeveloper108 commented on docs/porting-embed.md
> +| `donorProvider`               | N/A                         |
oooooooooff of course 🙈

2024-05-02 09:16 UTC, dharmadeveloper108 commented on src/PortingEmbed/CustomOptionsProvider.tsx
> +  renderDropdown?: (
In principle it could be any dropdown, not just specifically a providers one 🤔 I could just rename `providers` to `options` so it's more generic?

2024-05-02 09:33 UTC, gigsanna commented on src/PortingEmbed/CustomOptionsProvider.tsx
> +  renderDropdown?: (
oooooohhh, yep, `options` sounds reasonable 😄 See, description matters, I got confused too 🤣

2024-05-02 09:58 UTC, dharmadeveloper108 commented on src/components/Dropdown.tsx
> +    onSelect('')
we don't, leftover from me testing 😇

2024-05-03 10:37 UTC, gigsanna approved these changes
Great 🎉 Still have a questions about tests, but I don't think it should be blocking 😄 
<img src="https://media2.giphy.com/media/3a53VvGpzUgh05qq7W/giphy.gif"/>

2024-05-03 10:37 UTC, gigsanna commented on src/PortingEmbed/__tests__/DonorProviderForm.test.tsx
> +    let button
Is React-native version works differently, was my proposed solution with awaiting `find` now working properly?
```
const button = await screen.findByText('Save')
expect(button).toBeOnTheScreen()
expect(button).toBeDisabled()
```
There's also this ["Using waitFor to wait for elements that can be queried with find*"](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-waitfor-to-wait-for-elements-that-can-be-queried-with-find) rule suggesting that you'll get the same result with just using `find` queries, so now I'm wondering why not use that. Reassigning the value inside expect using waitFor + synchronous query method looks a bit weird to be honest, is this a react native flavour?

2024-05-03 10:41 UTC, dharmadeveloper108 commented on src/PortingEmbed/__tests__/DonorProviderForm.test.tsx
> +    let button
yeah it is a it awkward, it was just to not repeat `await screen.findByText('Save')` since that needed to be in the `waitfor`. But I'll give `find` a try!! 👀 could be the best way to go 👀

2024-05-03 12:56 UTC, dharmadeveloper108 commented on src/PortingEmbed/__tests__/DonorProviderForm.test.tsx
> +    let button
works like a charm @gigsanna thank you so much!! 👌 ✨ ⭐

2024-05-03 13:53 UTC, merged